family_tree/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainapp.urls')),
    url('', include('social_django.urls', namespace='social'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/urls.py
from .views import *

from django.urls import path

urlpatterns = [
    path('tree/<str:tree>/', BaseTreeView.as_view(), name='tree'),
    path('people/<str:slug>/', HumanDetailView.as_view(), name='human_detail'),
    path('search_result/', SearchResultView.as_view(), name='search_result'),
    path('change_info_human/<str:slug>/', ChangeHumanDetailView.as_view(), name='change_info_human'),
    path('save_human/<str:slug>/', SaveHuman.as_view(), name='save_human'),
    path('delete_human/<str:slug>/', DeleteHuman.as_view(), name='delete_human'),
    path('signup/', SignUpView.as_view(), name='signup'),
    path('user_info/<str:username>/', UserInfoView.as_view(), name='user_info'),
    path('change_info_user/<str:username>/', ChangeUserInfoView.as_view(), name='change_info_user'),
    path('delete_user/<str:username>/', DeleteUser.as_view(), name='delete_user'),
    path('', RedirectionBase.as_view(), name='redirection'),
    path('delete_tree/<str:tree>/', DeleteTree.as_view(), name='delete_tree'),
    path('login/', LoginUser.as_view(), name='login'),
    path('logout/', LogoutUser.as_view(), name='logout'),
    path('journal_tree/<str:tree>/', JournalTreeView.as_view(), name='journal_tree'),
    path('permission_user/<str:tree>/', PermissionUser.as_view(), name='permission_user'),
    path('termination_access/<str:tree>/<str:username>/', TerminationAccess.as_view(), name='termination_access'),
    path('delete_photo_human/<str:slug>/', DeletePhotoHuman.as_view(), name='delete_photo_human'),
    path('possible_trees/', PossibleTreesView.as_view(), name='possible_trees'),
    path('messages/', MessagesView.as_view(), name='user_messages'),
    path('permission_user_request/<str:tree>/<str:username>/<str:time>/', PermissionUser.as_view(), name='permission_user_request'),
    path('deviation_user_request/<str:tree>/<str:username>/<str:time>/', DeviationUser.as_view(), name='deviation_user_request'),
    path('send_access_request_tree/<str:tree>/', SendAccessRequestTree.as_view(), name='send_access_request_tree'),
    path('validate_username/', validate_username, name='validate_username'),
    path('related_relationships/<str:tree>/', related_relationships, name='related_relationships'),
    path('sunburst/', SunburstView.as_view(), name='sunburst'),
    path('potential_human/', PotentialHumanView.as_view(), name='potential_human'),
    path('read_messages_for_id/', read_messages_for_id, name='read_messages_for_id')
]

mainapp/models.py
from django.template.defaultfilters import slugify
from django.contrib.auth import get_user_model
from django.utils.safestring import mark_safe
from transliterate import translit
from django.urls import reverse
from django.db import models

User = get_user_model()


class Human(models.Model):
    first_name = models.CharField(
        max_length=255,
        verbose_name='Имя',
        null=True,
        blank=True
    )
    last_name = models.CharField(
        max_length=255,
        verbose_name='Фамилия',
        null=True,
        blank=True
    )
    image = models.ImageField(
        null=True,
        blank=True,
        verbose_name='Изображение',
        upload_to='human_face'
    )
    slug = models.SlugField(
        default=None,
        null=True,
        blank=True,
        verbose_name='Создаётся авт-ки'
    )
    parents = models.ManyToManyField(
        to='Human',
        verbose_name='Родители',
        blank=True
    )
    user = models.OneToOneField(
        to=User,
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        verbose_name='Пользователь (если есть)'
    )
    date_of_birth = models.DateField(
        verbose_name='Дата рождения',
        null=True
    )

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        slug = translit(
                f'{self.pk}_{self.__str__()}',
                'ru',
                reversed=True
            )
        self.slug = slugify(slug)
        super().save(*args, **kwargs)

    def __str__(self):
        if self.last_name.__str__() == 'None':
            return self.first_name.__str__()
        else:
            return f'{self.first_name.__str__()} {self.last_name.__str__()}'

    def get_absolute_url(self, name_path='human_detail'):
        return reverse(name_path, kwargs={
            'slug': self.slug
        })


class Tree(models.Model):
    humans = models.ManyToManyField(
        to=Human,
        verbose_name='Люди',
        related_name='trees'
    )
    user = models.ManyToManyField(
        to=User,
        verbose_name='Пользователь',
        related_name='trees'
    )
    potential_user = models.ManyToManyField(
        to=User,
        verbose_name='Ожидающие разрешения',
        related_name='potential_trees',
        null=True,
        blank=True
    )
    oldest_human = models.OneToOneField(
        to=Human,
        verbose_name='Прародитель',
        null=True,
        on_delete=models.SET_NULL,
        related_name='oldest_human'
    )
    creator = models.ForeignKey(
        to=User,
        verbose_name='Создатель',
        null=True,
        on_delete=models.SET_NULL,
        related_name='creator'
    )
    slug = models.SlugField(
        default=None,
        null=True,
        blank=True,
        unique=True,
        verbose_name='Слаг (создаётся авт-ки)'
    )

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        self.slug = slugify(translit(
            f'{self.pk}_descendants_of_{self.__str__()}',
            'ru',
            reversed=True)
        )
        print(self.user.first(), self.user.count())
        if self.user.count() == 1:
            self.creator = self.user.first()
        super().save(*args, **kwargs)

    def __str__(self):
        return self.oldest_human.__str__()

    def get_absolute_url(self, name_path='tree'):
        return reverse(name_path, kwargs={'tree': self.slug})

    def get_count_human(self):
        number = self.humans.all().count() - 1
        word = get_declination_from_numeral(number, 'потомок', 'потомка', 'потомков')
        return f'{number} {word}' if number > 0 else ''

    def get_count_users(self):
        number = self.user.count() - 1
        if number == 0:
            return 'в гордом одиночестве'
        word = get_declination_from_numeral(number, 'и ещё {} человек', 'и ещё {} человека', 'и ещё {} человек')
        return word.format(number) if number > 0 else ''

    def get_journal_url(self):
        return reverse('journal_tree', kwargs={'tree': self.slug})

    def get_short_name(self):
        return self.oldest_human.first_name[0] + self.oldest_human.last_name[0] if self.oldest_human.last_name else self.oldest_human.first_name[0]


class Message(models.Model):
    text = models.TextField(
        verbose_name='Содержание'
    )
    sender = models.ForeignKey(
        verbose_name='Отправитель',
        to=User,
        related_name='sender',
        on_delete=models.CASCADE
    )
    recipient = models.ForeignKey(
        verbose_name='Получатель',
        to=User,
        related_name='recipient',
        on_delete=models.CASCADE
    )
    sending_time = models.DateTimeField(
        verbose_name='Время отправки'
    )
    check_read_it = models.BooleanField(
        verbose_name='Прочитано',
        default=False
    )
    text_for_sender = models.TextField(
        verbose_name='Текст сообщения для отправляющего',
        default=''
    )

    @staticmethod
    def get_number_unread_messages(user):
        return len(Message.objects.filter(recipient=user, check_read_it=False))

    def get_mark_safe_text(self):
        return mark_safe(self.text)

    def get_mark_safe_text_for_sender(self):
        return mark_safe(self.text_for_sender)

    def __str__(self):
        return f'{self.sending_time.strftime("%H:%M %d.%m.%Y")}:  {self.sender.first_name} {self.sender.last_name} -> {self.recipient.first_name} {self.recipient.last_name}'


def get_declination_from_numeral(number, one, two, five):
    last_figure = number % 10
    return five if last_figure > 4 or 4 < number < 15 or last_figure == 0 else two if last_figure != 1 else one


class NumberChanges(models.Model):
    user = models.ForeignKey(
        verbose_name='Пользователь',
        to=User,
        on_delete=models.CASCADE,
        related_name='user'
    )
    tree = models.ForeignKey(
        verbose_name='Дерево',
        to=Tree,
        on_delete=models.CASCADE,
        related_name='tree'
    )
    number = models.IntegerField(
        verbose_name='Количество изменений'
    )

    def __str__(self):
        return f'{self.user} {self.tree} {self.number}'

mainapp/templates/change_human_info_page.html
{% extends 'base_tree_view_page.html' %}
{% block content %}
<script>
    var button_plus_child = '<div class="col"><button style="border-radius: 25px;" type="button" class="btn btn-outline-secondary btn-block btn-sm" onclick="addChild()"><svg width="2em" height="2em" viewBox="0 0 16 16" class="bi bi-person-plus" fill="currentColor" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M8 5a2 2 0 1 1-4 0 2 2 0 0 1 4 0zM6 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6zm6 5c0 1-1 1-1 1H1s-1 0-1-1 1-4 6-4 6 3 6 4zm-1-.004c-.001-.246-.154-.986-.832-1.664C9.516 10.68 8.289 10 6 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664h10zM13.5 5a.5.5 0 0 1 .5.5V7h1.5a.5.5 0 0 1 0 1H14v1.5a.5.5 0 0 1-1 0V8h-1.5a.5.5 0 0 1 0-1H13V5.5a.5.5 0 0 1 .5-.5z"/></svg></button></div>';
    var button_minus_child = '<div class="col"><button style="border-radius: 25px;" type="button" class="btn btn-outline-secondary btn-block btn-sm" onclick="deleteChild()"><svg width="2em" height="2em" viewBox="0 0 16 16" class="bi bi-person-dash" fill="currentColor" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M8 5a2 2 0 1 1-4 0 2 2 0 0 1 4 0zM6 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6zm6 5c0 1-1 1-1 1H1s-1 0-1-1 1-4 6-4 6 3 6 4zm-1-.004c-.001-.246-.154-.986-.832-1.664C9.516 10.68 8.289 10 6 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664h10zM11 7.5a.5.5 0 0 1 .5-.5h4a.5.5 0 0 1 0 1h-4a.5.5 0 0 1-.5-.5z"/></svg></button></div>';
    var buttons_plus_and_minus_child = button_plus_child + button_minus_child;
    var button_plus_parent = '<div class="col"><button style="border-radius: 25px;" type="button" class="btn btn-outline-secondary btn-block btn-sm" onclick="addParent()"><svg width="2em" height="2em" viewBox="0 0 16 16" class="bi bi-person-plus" fill="currentColor" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M8 5a2 2 0 1 1-4 0 2 2 0 0 1 4 0zM6 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6zm6 5c0 1-1 1-1 1H1s-1 0-1-1 1-4 6-4 6 3 6 4zm-1-.004c-.001-.246-.154-.986-.832-1.664C9.516 10.68 8.289 10 6 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664h10zM13.5 5a.5.5 0 0 1 .5.5V7h1.5a.5.5 0 0 1 0 1H14v1.5a.5.5 0 0 1-1 0V8h-1.5a.5.5 0 0 1 0-1H13V5.5a.5.5 0 0 1 .5-.5z"/></svg></button></div>';
    var button_minus_parent = '<div class="col"><button style="border-radius: 25px;" type="button" class="btn btn-outline-secondary btn-block btn-sm" onclick="deleteParent()"><svg width="2em" height="2em" viewBox="0 0 16 16" class="bi bi-person-dash" fill="currentColor" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M8 5a2 2 0 1 1-4 0 2 2 0 0 1 4 0zM6 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6zm6 5c0 1-1 1-1 1H1s-1 0-1-1 1-4 6-4 6 3 6 4zm-1-.004c-.001-.246-.154-.986-.832-1.664C9.516 10.68 8.289 10 6 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664h10zM11 7.5a.5.5 0 0 1 .5-.5h4a.5.5 0 0 1 0 1h-4a.5.5 0 0 1-.5-.5z"/></svg></button></div>';
    var buttons_plus_and_minus_parent = button_plus_parent + button_minus_parent;
    var x_child = 0;
    var x_parent = 0;
</script>
<div class="container shadow" style="padding: 35px 40px 35px 40px; width: 1000px">
    <h1 class="display-4">Человек</h1>
    <br>
    <form method="POST" enctype="multipart/form-data" action="{{ save_human }}">
        {% csrf_token %}
        <div class="row">
            <div class="col-3">
                <input class="shadow form-control" type="date" value="{{ human.date_of_birth|date:'Y-m-d' }}" name="date_of_birth">
            </div>
            <div class="col">
                <input type="text" class="shadow form-control" placeholder="Имя" required id="id_first_name" name="first_name" value="{{ human.first_name }}">
            </div>
            <div class="col">
                <input type="text" class="shadow form-control" placeholder="Фамилия" id="id_last_name" name="last_name" value="{{ human.last_name }}">
            </div>
            {% if human.image %}
            <div class="image-upload" data-toggle="tooltip" title="Изменить фото">
                <label for="id_image_human">
                    <div class="photo_page" style="
                                           width: 36px;
                                           height: 36px;">
                        <img class="personPhoto" src="{{ human.image.url }}">
                    </div>
                </label>
                <input  name="image_human" id="id_image_human" type="file" value="{{ human.image.url }}"/>
            </div>
            {% else %}
            <div class="image" align="center">
                <div class="form-group" style="margin:0,padding:0">
                    <label for="id_image_human" class="label" style="height:38px">
                        <i class="material-icons">attach_file</i>
                        <input type="file" name="image_human" accept="image/*" id="id_image_human">
                    </label>
                </div>
            </div>
            {% endif %}
        </div>
        <br>
        <h1 class="display-4">Родители</h1>
        <br>
        <div_input id="parent0"></div_input>
        <div class="row" id="buttons-change-parent"></div>
        {% if human.parents.all %}
        {% for parent in human.parents.all %}
        <script>
            var str = '<div_child_row class="row"><div class="col-3"><input class="shadow form-control" type="date" value="{{ parent.date_of_birth|date:'Y-m-d' }}" name="date_of_birth_parent' + x_parent + '"></div><div class="col"><input type="text" class="shadow form-control" placeholder="Имя" name="first_name_parent' + x_parent + '" required value="{{ parent.first_name }}" readonly></div><div class="col"><input type="text" class="shadow form-control" placeholder="Фамилия" name="last_name_parent' + x_parent + '" value="{% if parent.last_name == "None" %}{% else%}{{ parent.last_name }}{% endif %}" readonly></div>        {% if parent.image %}<div class="image-upload" ><label for="id_image_parent' + x_parent + '"><div class="photo_page" style="width: 36px;height: 36px;"><img class="personPhoto" src="{{ parent.image.url }}"></div></label><input  name="image_parent' + x_parent + '" id="id_image_parent' + x_parent + '" type="file" /></div>{% else %}<div class="image" align="center"><div class="form-group" style="margin:0,padding:0"><label for="id_image_parent' + x_parent + '" class="label" style="height:38px"><i class="material-icons">attach_file</i><input type="file" name="image_parent' + x_parent + '" accept="image/*" id="id_image_parent' + x_parent + '"></label></div></div>{% endif %}</div_child_row><div_input id="parent' + (x_parent+1) + '"></div_input>';
            if (x_parent == 0) {
                document.getElementById('parent' + x_parent).innerHTML = str + '<br>';
            }
            else {
                document.getElementById('parent' + x_parent).innerHTML = str;
             }
            x_parent++;
        </script>
        {% endfor %}
        {% endif %}
        <script>
            if (x_parent != 2) {
                document.getElementById('buttons-change-parent').innerHTML = button_plus_parent;
            }
            var x_min_parent = x_parent;
        </script>
        <br>
        <h1 class="display-4">Дети</h1>
        <br>
        <div_input id="child0"></div_input>
        <div class="row" id="buttons-change-childrens"></div>
        {% if children %}
        {% for child in children %}
        <script>
            var str = '<div_child_row class="row"><div class="col-3"><input class="shadow form-control" type="date" value="{{ child.date_of_birth|date:'Y-m-d' }}" name="date_of_birth_child' + x_child + '"></div><div class="col"><input type="text" class="shadow form-control" placeholder="Имя" name="first_name_child' + x_child + '" required id="id_first_name_child' + x_child + '" value="{{ child.first_name }}" readonly></div><div class="col"><input type="text" class="shadow form-control" placeholder="Фамилия" name="last_name_child' + x_child + '" id="id_last_name_child' + x_child + '" value="{% if child.last_name == "None" %}{% else%}{{ child.last_name }}{% endif %}" readonly></div>        {% if child.image %}<div class="image-upload" ><label for="id_image_child' + x_child + '"><div class="photo_page" style="width: 36px;height: 36px;"><img class="personPhoto" src="{{ child.image.url }}"></div></label><input  name="image_child' + x_child + '" id="id_image_child' + x_child + '" type="file" /></div>{% else %}<div class="image" align="center"><div class="form-group" style="margin:0,padding:0"><label for="id_image_child' + x_child + '" class="label" style="height:38px"><i class="material-icons">attach_file</i><input type="file" name="image_child' + x_child + '" accept="image/*" id="id_image_child' + x_child + '"></label></div></div>{% endif %}</div_child_row><div_input id="child' + (x_child+1) + '"></div_input>';
            if (x_child == 0) {
                document.getElementById('child' + x_child).innerHTML = str + '<br>';
            }
            else {
                document.getElementById('child' + x_child).innerHTML = str;
             }
            x_child++;
        </script>
        {% endfor %}
        {% endif %}
        <script>
            var x_min_child = x_child;
            document.getElementById('buttons-change-childrens').innerHTML = button_plus_child;
        </script>
        <br><br>
        <button type="submit" class="shadow btn btn-success btn-block my_button" style="border-radius:20px;">Сохранить</button>

    </form>
</div>
<script>
function addChild() {
	if (x_child < 20) {
        var str_child = '<div_child_row class="row"><div class="col-3"><input class="shadow form-control" type="date" name="date_of_birth_child' + x_child + '"></div><div class="col"><input type="text" class="form-control" placeholder="Имя" name="first_name_child' + x_child + '" required id="id_first_name_child' + x_child + '"></div><div class="col"><input type="text" class="form-control" placeholder="Фамилия" name="last_name_child' + x_child + '" id="id_last_name_child' + x_child + '"></div>         <div class="image" align="center"><div class="form-group" style="margin:0,padding:0"><label for="id_image_child' + x_child + '" class="label" style="height:38px"><i class="material-icons">attach_file</i><input type="file" name="image_child' + x_child + '" accept="image/*" id="id_image_child' + x_child + '"></label></div></div>          </div_child_row>';
        var new_div = '<div_input id="child' + (x_child+1) + '"></div_input>'
        if (x_child == x_min_child) {
            document.getElementById('child' + x_child).innerHTML = str_child + new_div + '<br>';
            document.getElementById('buttons-change-childrens').innerHTML = buttons_plus_and_minus_child;
        }
        else {
            document.getElementById('child' + x_child).innerHTML = str_child + new_div;
        }
        x_child++;
    }
    else {
        document.getElementById('buttons-change-childrens').innerHTML = button_minus_child;
        alert('Вот это да! К сожалению пока для меня немыслимо такое количество детей');
    }
}

function deleteChild() {
    if (x_child == 20) {
        document.getElementById('buttons-change-childrens').innerHTML = buttons_plus_and_minus_child;
    }
    if (x_child == x_min_child + 1) {
        document.getElementById('buttons-change-childrens').innerHTML = button_plus_child;
    }
    document.getElementById('child' + x_child).remove();
	document.getElementById('child' + (x_child - 1)).innerHTML = '<div id="input' + (x_child-1) + '"></div>';
    x_child--;
}

function addParent() {
    var str_parent = '<div_child_row class="row"><div class="col-3"><input class="shadow form-control" type="date" name="date_of_birth_parent' + x_parent + '"></div><div class="col"><input type="text" class="shadow form-control" placeholder="Имя" required name="first_name_parent' + x_parent + '"></div><div class="col"><input type="text" class="shadow form-control" placeholder="Фамилия" name="last_name_parent' + x_parent + '"></div><div class="image" align="center"><div class="form-group" style="margin:0,padding:0"><label for="id_image_parent' + x_parent + '" class="label" style="height:38px"><i class="material-icons">attach_file</i><input type="file" name="image_parent' + x_parent + '" accept="image/*" id="id_image_parent' + x_parent + '"></label></div></div></div_child_row>';
    var new_div = '<div_input id="parent' + (x_parent+1) + '"></div_input>';
    if (x_parent == x_min_parent) {
        document.getElementById('parent' + x_parent).innerHTML = str_parent + new_div + '<br>';
    }
    else {
        document.getElementById('parent' + x_parent).innerHTML = str_parent + new_div;
    }
    x_parent++;
    if (x_parent < 2) {
        document.getElementById('buttons-change-parent').innerHTML = buttons_plus_and_minus_parent;
    }
    else
    {
        document.getElementById('buttons-change-parent').innerHTML = button_minus_parent;
    }
}

function deleteParent() {
    document.getElementById('parent' + x_parent).remove();
	document.getElementById('parent' + (x_parent - 1)).innerHTML = '<div id="input' + (x_parent-1) + '"></div>';
    x_parent--;
    if (x_parent == x_min_parent) {
        document.getElementById('buttons-change-parent').innerHTML = button_plus_parent;
    }
    else {
        document.getElementById('buttons-change-parent').innerHTML = buttons_plus_and_minus_parent;
    }
}
</script>
{% endblock content %}

mainapp/templates/search_result_page.html
{% extends 'base_tree_view_page.html' %}
{% block content %}

<div class="container shadow">
    {% if object_list or users_list %}
        {% if object_list %}
            <h1 class="display-3" style="padding-top: 20px">Люди из Ваших деревьев:</h1>
            {% for object in object_list %}
                <h1 class="display-4"><a href="{{ object.get_absolute_url }}"> {{ object }} </a></h1>
            {% endfor %}
            <br>
        {% endif %}
        {% if users_list %}
            <h1 class="display-3" style="padding-top: 20px">Пользователи:</h1>
            {% for object in users_list %}
                <h1 class="display-4">
                    <a href="/user_info/{{ object }}/"> {{ object.first_name }} {{ object.last_name }}
                        {% if object.first_name == user.first_name and object.last_name == user.last_name %}
                            - это Вы
                        {% endif %}
                    </a>
                </h1>
            {% endfor %}
        {% endif %}
    {% else %}
        <h1 class="display-4" style="padding-top: 30px"> Поиск не дал результатов ¯\_(ツ)_/¯</h1>
    {% endif %}
</div>

{% endblock content %}

mainapp/templates/sunburst_relatives.html
{% extends 'base_tree_view_page.html' %}
{% block content %}
<div class="container shadow" style="min-width:600px; padding-right: 50px">
    <div id="anychart-embed-rBNxDPlf" class="anychart-embed anychart-embed-rBNxDPlf">
        <script src="https://cdn.anychart.com/releases/8.9.0/js/anychart-base.min.js?hcode=a0c21fc77e1449cc86299c5faa067dc4"></script>
        <script src="https://cdn.anychart.com/releases/8.9.0/js/anychart-sunburst.min.js?hcode=a0c21fc77e1449cc86299c5faa067dc4"></script>
        <script src="https://cdn.anychart.com/releases/8.9.0/js/anychart-exports.min.js?hcode=a0c21fc77e1449cc86299c5faa067dc4"></script>
        <script src="https://cdn.anychart.com/releases/8.9.0/js/anychart-ui.min.js?hcode=a0c21fc77e1449cc86299c5faa067dc4"></script>
        <div id="ac_style_rBNxDPlf" style="display:none;" data-json="{{ sunburstJSON }}">

        </div>
        <script>(function(){
    function ac_add_to_head(el){
        var head = document.getElementsByTagName('head')[0];
        head.insertBefore(el,head.firstChild);
    }
    function ac_add_link(url){
        var el = document.createElement('link');
        el.rel='stylesheet';el.type='text/css';el.media='all';el.href=url;
        ac_add_to_head(el);
    }
    function ac_add_style(css){
        var ac_style = document.createElement('style');
        if (ac_style.styleSheet) ac_style.styleSheet.cssText = css;
        else ac_style.appendChild(document.createTextNode(css));
        ac_add_to_head(ac_style);
    }
    ac_add_link('https://cdn.anychart.com/releases/8.9.0/css/anychart-ui.min.css?hcode=a0c21fc77e1449cc86299c5faa067dc4');
    ac_add_style(document.getElementById("ac_style_rBNxDPlf").innerHTML);
    ac_add_style(".anychart-embed-rBNxDPlf{width:100%;height:100%;}");
    })();
        </script>
        <div id="sun_container" style="height: 500px"></div>
        <script>
    anychart.onDocumentReady(function () {
        var data = JSON.parse(
            document.querySelector("#ac_style_rBNxDPlf").getAttribute('data-json')
        );

        var chart = anychart.sunburst(data, "as-tree");

        chart.title().useHtml(true);
        chart.startAngle(90);
        chart.tooltip().format("{%who}");
        chart.labels().position("circular");
        chart.background().enabled(true);
        chart.background().fill("#a5bbb8 1.0");

        chart.container("sun_container");
        chart.draw();
    });

        </script>
</div>
{% endblock content %}